% Test 4 - Check balance and gravity constraints within a 2x4x2 cuboid without consideration to gravity

left(x1,x2).
below(y1,y2).
below(y2,y3).
below(y3,y4).
before(z1,z2).


container(c1,x2,y1,z1).
container(c1,x2,y1,z2).
container(c2,x1,y1,z1).
container(c2,x1,y1,z2).

container(c3,x1,y2,z1).
container(c3,x1,y3,z1).
container(c4,x1,y2,z2).
container(c4,x1,y3,z2).

container(c5,x2,y2,z1).
container(c5,x2,y3,z1).
container(c6,x2,y2,z2).
container(c6,x2,y3,z2).

container(c7,x1,y4,z1).
container(c7,x2,y4,z1).
container(c8,x1,y4,z2).
container(c8,x2,y4,z2).


xsum(y1,z1,2). xsum(y1,z2,1).
xsum(y2,z1,2). xsum(y2,z2,1).
xsum(y3,z1,2). xsum(y3,z2,1).
xsum(y4,z1,2). xsum(y4,z2,1).

ysum(x1,z1,4). ysum(x1,z2,2).
ysum(x2,z1,4). ysum(x2,z2,2).

zsum(x1,y1,1). zsum(x2,y1,2).
zsum(x1,y2,2). zsum(x2,y2,1).
zsum(x1,y3,1). zsum(x2,y3,2).
zsum(x1,y4,2). zsum(x2,y4,1).
