% Test 3 - Check balance and gravity constraints within a 2x2x2 cube

left(x1,x2).
below(y1,y2).
before(z1,z2).


%check if it works when some grids have no containers
container(c1,x1,y1,z1).
container(c1,x1,y2,z1).
container(c2,x2,y1,z1).
container(c3,x2,y2,z1).
container(c4,x2,y1,z2).
container(c4,x2,y2,z2).


%check if it works when not all w-axis are declared (more freedom when filling)
xsum(y1,z1,1). xsum(y1,z2,1).
xsum(y2,z1,2). xsum(y2,z2,1).